channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=23.2.1
- pip:
  - mlflow==2.7.1
  - catboost==1.2
  - cloudpickle==2.2.1
  - colorama==0.4.6
  - configparser==5.3.0
  - importlib-metadata==6.0.0
  - ipywidgets==8.0.4
  - lz4==4.3.2
  - numpy==1.24.3
  - packaging==23.0
  - pandas==2.0.3
  - pathlib==1.0.1
  - pyyaml==6.0
  - scikit-learn==1.3.0
  - scipy==1.11.1
  - xgboost==1.7.6
name: mlflow-env
